DATA:
  IMG_SIZE: 256
MODEL:
  TYPE: swinv2_dense_res3_Q
  NAME: dense_deit_Q_Res3_uniform_1_relu_tiny_patch16_224

  DROP_PATH_RATE: 0.5
  SWINV2:
    EMBED_DIM: 128
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 4, 8, 16, 32 ]
    WINDOW_SIZE: 16