DATA:
  IMG_SIZE: 256
MODEL:
  TYPE: swinv2_dense_res3_Q
  NAME: dense_deit_Q_Res3_uniform_1_relu_tiny_patch16_224
  DROP_PATH_RATE: 0.0
  SWINV2:
    EMBED_DIM: 96
    DEPTHS: [ 2, 2, 6, 2 ]
    NUM_HEADS: [ 3, 6, 12, 24 ]
    WINDOW_SIZE: 8